--Insertar cliente
CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE (
    ID_IN IN NUMBER,
    NOMBRE_IN VARCHAR2,
    APELLIDO_IN VARCHAR2,
    TEL_IN VARCHAR2,
    EMAIL_IN VARCHAR2
) IS 
BEGIN
    INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, TELEFONO, EMAIL) 
    VALUES (ID_IN, NOMBRE_IN, APELLIDO_IN, TEL_IN, EMAIL_IN);
    COMMIT;
END;
/

--Modificar cliente
CREATE OR REPLACE PROCEDURE MODIFICA_CLIENTE (
    V_ID IN NUMBER, V_NOMBRE IN VARCHAR2, V_APELLIDO IN VARCHAR2, 
    V_TEL IN VARCHAR2, V_EMAIL IN VARCHAR2
) AS 
BEGIN
    UPDATE CLIENTES 
    SET NOMBRE = V_NOMBRE, 
        APELLIDO = V_APELLIDO, 
        TELEFONO = V_TEL, 
        EMAIL = V_EMAIL 
    WHERE ID_CLIENTE = V_ID;
    COMMIT;
END;
/

--Eliminar cliente
CREATE OR REPLACE PROCEDURE BORRAR_CLIENTE(ID_CLI IN NUMBER) AS 
BEGIN
    DELETE FROM CLIENTES WHERE ID_CLIENTE = ID_CLI;
    COMMIT;
END;
/

--Listar clientes
CREATE OR REPLACE PROCEDURE GET_CLIENTES (C_CLIENTES OUT SYS_REFCURSOR) 
AS 
BEGIN
    OPEN C_CLIENTES FOR SELECT * FROM CLIENTES;
END;
/

--Insertar categoría
CREATE OR REPLACE PROCEDURE ADD_CATEGORIA (
    ID_CAT IN NUMBER, 
    NOM_CAT IN VARCHAR2
) IS 
BEGIN
    INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA) 
    VALUES (ID_CAT, NOM_CAT);
    COMMIT;
END;
/

--Modificar categoría
CREATE OR REPLACE PROCEDURE UPDATE_CATEGORIA (
    ID_CAT IN NUMBER, NOM_CAT IN VARCHAR2
) AS 
BEGIN
    UPDATE CATEGORIAS 
    SET NOMBRE_CATEGORIA = NOM_CAT 
    WHERE ID_CATEGORIA = ID_CAT;
    COMMIT;
END;
/

--Eliminar categoría
CREATE OR REPLACE PROCEDURE ELIMINAR_CAT (ID_CAT IN NUMBER) 
IS 
BEGIN
    DELETE FROM CATEGORIAS WHERE ID_CATEGORIA = ID_CAT;
    COMMIT;
END;
/

--Listar categorías
CREATE OR REPLACE PROCEDURE LISTAR_CATEGORIAS (CURSOR_CAT OUT SYS_REFCURSOR) AS 
BEGIN
    OPEN CURSOR_CAT FOR SELECT * FROM CATEGORIAS;
END;
/

--Insertar producto
CREATE OR REPLACE PROCEDURE SP_NUEVO_PRODUCTO (
    V_ID_PROD NUMBER, 
    V_ID_CAT NUMBER, 
    V_NOMBRE VARCHAR2, 
    V_DESC VARCHAR2, 
    V_PRECIO NUMBER
) AS 
BEGIN
    INSERT INTO PRODUCTOS (ID_PRODUCTO, ID_CATEGORIA, NOMBRE, DESCRIPCION, PRECIO_VENTA) 
    VALUES (V_ID_PROD, V_ID_CAT, V_NOMBRE, V_DESC, V_PRECIO);
    COMMIT;
END;
/

--Modificar producto
CREATE OR REPLACE PROCEDURE SP_EDITAR_PRODUCTO (
    V_ID_PROD NUMBER, V_ID_CAT NUMBER, V_NOMBRE VARCHAR2, 
    V_DESC VARCHAR2, V_PRECIO NUMBER
) IS 
BEGIN
    UPDATE PRODUCTOS 
    SET ID_CATEGORIA = V_ID_CAT, 
        NOMBRE = V_NOMBRE, 
        DESCRIPCION = V_DESC, 
        PRECIO_VENTA = V_PRECIO 
    WHERE ID_PRODUCTO = V_ID_PROD;
    COMMIT;
END;
/

--Eliminar producto
CREATE OR REPLACE PROCEDURE SP_BORRAR_PRODUCTO(V_ID_PROD IN NUMBER) 
AS 
BEGIN
    DELETE FROM PRODUCTOS WHERE ID_PRODUCTO = V_ID_PROD;
    COMMIT;
END;
/

--Listar productos
CREATE OR REPLACE PROCEDURE VER_PRODUCTOS (C_PROD OUT SYS_REFCURSOR) 
IS 
BEGIN
    OPEN C_PROD FOR SELECT * FROM PRODUCTOS;
END;
/

-- Reporte de inventario
CREATE OR REPLACE PROCEDURE REPORTE_INVENTARIO(C_INV OUT SYS_REFCURSOR) 
AS 
BEGIN
    OPEN C_INV FOR SELECT * FROM INVENTARIO;
END;
/